/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'First Steps',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.05,
      timeLimitSeconds: null,
      targetScore: 500,
      obstacleCount: 5,
      obstacleSpeed: 0,
      collectibleCount: 3,
      collectibleValue: 100,
      backgroundTheme: 'sunny_meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Learning to Leap',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.1,
      timeLimitSeconds: null,
      targetScore: 1000,
      obstacleCount: 5,
      obstacleSpeed: 1,
      collectibleCount: 5,
      collectibleValue: 150,
      backgroundTheme: 'sunny_meadow',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'The First Challenge',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.15,
      timeLimitSeconds: null,
      targetScore: 1500,
      obstacleCount: 5,
      obstacleSpeed: 1,
      collectibleCount: 7,
      collectibleValue: 200,
      backgroundTheme: 'sunny_meadow',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Rising Difficulty',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.2,
      timeLimitSeconds: 120,
      targetScore: 2000,
      obstacleCount: 10,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 250,
      backgroundTheme: 'cloudy_heights',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Midway Madness',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.3,
      timeLimitSeconds: 120,
      targetScore: 2500,
      obstacleCount: 15,
      obstacleSpeed: 2,
      collectibleCount: 5,
      collectibleValue: 500,
      backgroundTheme: 'cloudy_heights',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Twists and Turns',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.4,
      timeLimitSeconds: 90,
      targetScore: 3000,
      obstacleCount: 20,
      obstacleSpeed: 2,
      collectibleCount: 7,
      collectibleValue: 550,
      backgroundTheme: 'night_sky',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'The Labyrinth',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 90,
      targetScore: 3500,
      obstacleCount: 25,
      obstacleSpeed: 2,
      collectibleCount: 9,
      collectibleValue: 600,
      backgroundTheme: 'night_sky',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Rapid Reflections',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 60,
      targetScore: 4000,
      obstacleCount: 30,
      obstacleSpeed: 3,
      collectibleCount: 11,
      collectibleValue: 650,
      backgroundTheme: 'cosmic_void',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'The Gauntlet',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.75,
      timeLimitSeconds: 60,
      targetScore: 4500,
      obstacleCount: 35,
      obstacleSpeed: 3,
      collectibleCount: 5,
      collectibleValue: 1000,
      backgroundTheme: 'cosmic_void',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Mastermind',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 45,
      targetScore: 5000,
      obstacleCount: 40,
      obstacleSpeed: 4,
      collectibleCount: 7,
      collectibleValue: 1100,
      backgroundTheme: 'cosmic_void',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
